package com.infy.billing.enums;

public enum Status {
	// ENTITY
	ACTIVE, INACTIVE, SUSPENDED,
	
	// SUBSCRIPTION
	DRAFT, TRIALING, PAST_DUE, PAUSED, CANCELED, ON_HOLD,
	
	// INVOICE
	OPEN, PAID, VOID, UNCOLLECTIBLE,
	
	// PAYMENT
	PENDING, SUCCESS, FAILED, REFUNDED, PARTIALLY_REFUNDED,
	
	// CREDIT NOTE
	ISSUED, APPLIED, VOIDED,
	
	// COUPON/PAYMENT METHOD
	EXPIRED, REVOKED, DISABLED,
	
	// NOTIF
	SENT, SKIPPED
}
